#!/usr/bin/env bash


## SETTINGS ##
CURRENCY='      usdt str'
AMOUNT='        50'

#RATE='          .7'
#FILLAT='        .781'
#STOPLOSS='      .6794'
SL_FAST='        1.001'

RISK='          1.5'
PROFIT='        2'

#FAKE='          yes'
#HALFP='         yes'

################################################################################
TRADE='python2.7 trade.py '

if [[ ! -z $CURRENCY ]]; then
  TRADE="$TRADE"' --currency '"$CURRENCY"' '
fi

if [[ ! -z $AMOUNT ]]; then
  TRADE="$TRADE"' --amount '"$AMOUNT"' '
fi

if [[ ! -z $RATE ]]; then
  TRADE="$TRADE"' --buy-rate '"$RATE"' '
fi

if [[ ! -z $RISK ]]; then
  TRADE="$TRADE"' --risk '"$RISK"' '
fi

if [[ ! -z $PROFIT ]]; then
  TRADE="$TRADE"' --profit '"$PROFIT"' '
fi

if [[ ! -z $STOPLOSS ]]; then
  TRADE="$TRADE"' --sl-rate '"$STOPLOSS"' '
fi

if [[ ! -z $FILLAT ]]; then
  TRADE="$TRADE"' --full-rate '"$FILLAT"' '
fi

if [[ ! -z $FAKE ]]; then
  TRADE="$TRADE"' --fake '"$FAKE"' '
fi

if [[ ! -z $HALFP ]]; then
  TRADE="$TRADE"' --halfp '"$HALFP"' '
fi

if [[ ! -z $SL_FAST ]]; then
  TRADE="$TRADE"' --sl-fast '"$SL_FAST"' '
fi

echo $TRADE
eval $TRADE
################################################################################
