#!/usr/bin/env bash


# SETTINGS
  CURRENCY='      usdt str'
  AMOUNT='        5'
#  RATE='          .2'
  RISK='          2'
  PROFIT='        1'
#  STOPLOSS='      .25'
#  FILLAT='        .75'
#  FAKE='          yes'

################################################################################
TRADE='python2.7 trade.py '

if [[ ! -z $CURRENCY ]]; then
  TRADE="$TRADE"' --currency '"$CURRENCY"' '
fi

if [[ ! -z $AMOUNT ]]; then
  TRADE="$TRADE"' --amount '"$AMOUNT"' '
fi

if [[ ! -z $RATE ]]; then
  TRADE="$TRADE"' --buy-rate '"$RATE"' '
fi

if [[ ! -z $RISK ]]; then
  TRADE="$TRADE"' --risk '"$RISK"' '
fi

if [[ ! -z $PROFIT ]]; then
  TRADE="$TRADE"' --profit '"$PROFIT"' '
fi

if [[ ! -z $STOPLOSS ]]; then
  TRADE="$TRADE"' --sl-rate '"$STOPLOSS"' '
fi

if [[ ! -z $FILLAT ]]; then
  TRADE="$TRADE"' --full-rate '"$FILLAT"' '
fi

if [[ ! -z $FAKE ]]; then
  TRADE="$TRADE"' --fake '"$FAKE"' '
fi

echo $TRADE
eval $TRADE
################################################################################
